import {createWorkspace,uid,STATUSES,getStageProgress,getTaskProgress} from './data.js';
import {OrotSync} from './sync.js';

const DATA_KEY='orot_hr_workspace_v1', BACKUP_KEY='orot_hr_workspace_rollback_v1';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nl=v=>esc(v).replace(/\n/g,'<br>');
const dt=v=>v?new Date(v).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const clip=v=>String(v||'').slice(0,2500);
const choose=(opts,v)=>Object.entries(opts).map(([key,name])=>`<option value="${esc(key)}" ${v===key?'selected':''}>${esc(name)}</option>`).join('');
const btn=(name,action,extra='',style='ghost')=>`<button type="button" class="btn ${style}" data-action="${action}" ${extra}>${name}</button>`;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),3400)}
function confirmDanger(message){return window.confirm(message)}
function isValidWorkspace(w){return w && w.schemaVersion===1 && Array.isArray(w.stages)&&Array.isArray(w.tasks)&&Array.isArray(w.trash)}
function readWorkspace(){
 try{const data=localStorage.getItem(DATA_KEY); if(!data)return createWorkspace();const w=JSON.parse(data);if(isValidWorkspace(w))return w;}catch(e){console.error('local data error',e);}
 const fallback=localStorage.getItem(BACKUP_KEY); if(fallback){try{const w=JSON.parse(fallback);if(isValidWorkspace(w)){toast('손상된 기록 대신 이전 백업을 복구했습니다.');return w}}catch{}}
 alert('저장된 데이터를 읽지 못했습니다. 브라우저 데이터를 삭제하지 말고 백업 파일을 확인해주세요.');return createWorkspace();
}
let ws=readWorkspace(),view='home',selectedId=null,activeFilter='all',search='',sideOpen=false;
const expanded=new Set(ws.stages.map(s=>s.id)); const groupOpen=new Set();
let storageOk=true;
try{selectedId=localStorage.getItem('orot_hr_last_task')||ws.tasks[0]?.id;}catch{}
function writeLocal(){
 ws.updatedAt=new Date().toISOString();
 try{const old=localStorage.getItem(DATA_KEY);if(old&&old.length<3_500_000)localStorage.setItem(BACKUP_KEY,old);localStorage.setItem(DATA_KEY,JSON.stringify(ws));storageOk=true;return true;}
 catch(e){storageOk=false;alert('저장 공간 오류: 이번 변경을 디스크에 저장하지 못했습니다. 설정에서 백업을 내보내 공간을 확인해주세요.');console.error(e);return false;}
}
if(!localStorage.getItem(DATA_KEY)) writeLocal();
const sync=new OrotSync({getSnapshot:()=>ws, replaceSnapshot:w=>{if(!isValidWorkspace(w))throw Error('유효하지 않은 서버 데이터입니다.');ws=structuredClone(w);if(!writeLocal())throw Error('로컬 저장 오류');render();toast('서버의 새 기록을 불러왔습니다.');},notify:()=>updateSync()});
function updateSync(){const el=$('#sync-status');if(el){el.textContent=!storageOk?'로컬 저장 오류':sync.label();el.title='현재 데이터 저장 상태';el.classList.toggle('warn',sync.conflict||!storageOk||sync.label().includes('실패'));}}
function track(label){ws.activity.unshift({id:uid(),label,time:new Date().toISOString()});ws.activity=ws.activity.slice(0,80)}
function change(label,fn){fn();track(label);if(writeLocal()){sync.markChanged();render();}else render();}
function stageTasks(id){return ws.tasks.filter(t=>t.stageId===id)}
function taskById(id){return ws.tasks.find(t=>t.id===id)}
function groupById(t,gid){return t?.groups.find(g=>g.id===gid)}
function itemById(t,gid,iid){return groupById(t,gid)?.items.find(i=>i.id===iid)}
function selectTask(id){selectedId=id;view='task';search='';sideOpen=false;try{localStorage.setItem('orot_hr_last_task',id)}catch{}render();window.scrollTo(0,0)}
function go(v){view=v;search='';sideOpen=false;render();window.scrollTo(0,0)}
function progressBar(p){return `<div class="progress"><span style="width:${p??0}%"></span></div>`}
function dots(status){return `<span class="status-dot s-${esc(status)}"></span>`}
function countStats(){let arr=ws.tasks.filter(t=>t.status!=='not_applicable'),total=arr.length,done=arr.filter(t=>t.status==='complete').length;return {total,done,inProgress:arr.filter(t=>t.status==='in_progress').length,waiting:arr.filter(t=>t.status==='waiting').length,percent:total?Math.round(done/total*100):null};}
function selectedFilter(tasks){return tasks.filter(t=>activeFilter==='all'||t.status===activeFilter);}
function renderNav(){
 return `<aside class="sidebar ${sideOpen?'show':''}">
 <div class="brand"><img src="./icons/icon-192.png" alt="OROT HR"/><div><strong>OROT HR</strong><small>오롯한 인사체계의 시작</small></div><button class="mobile-close" data-action="close-menu" aria-label="메뉴 닫기">✕</button></div>
 <div class="space-label">MY WORKSPACE</div>
 <button class="nav-main ${view==='home'?'active':''}" data-action="go" data-view="home"><span class="nav-ico">⌂</span>대시보드</button>
 <div class="stage-label">HR 구축 단계 <span>4 STAGES</span></div>
 <div class="nav-stages">${ws.stages.map((s,idx)=>{
  const p=getStageProgress(ws,s.id);const op=expanded.has(s.id);
  return `<div class="nav-stage"><button class="stage-title" data-action="toggle-stage" data-stage="${s.id}"><span class="stage-num">0${idx+1}</span><span class="stage-caption">${esc(s.name)}</span><span class="chevron">${op?'⌄':'›'}</span></button><div class="stage-nav-progress">${progressBar(p.percent)}<small>${p.done}/${p.total}</small></div>
  ${op?`<div class="task-nav">${stageTasks(s.id).map(t=>`<button class="task-nav-link ${view==='task'&&selectedId===t.id?'selected':''}" data-action="open-task" data-task="${t.id}">${dots(t.status)}<span>${esc(t.title)}</span></button>`).join('')}
  <button class="add-inline" data-action="add-task" data-stage="${s.id}">＋ 새 업무 추가</button></div>`:''}</div>`}).join('')}</div>
 <div class="nav-utilities"><button class="nav-main ${view==='library'?'active':''}" data-action="go" data-view="library"><span class="nav-ico">▤</span>자료 모음</button><button class="nav-main ${view==='trash'?'active':''}" data-action="go" data-view="trash"><span class="nav-ico">♧</span>휴지통 <span class="aside-count">${ws.trash.length||''}</span></button><button class="nav-main ${view==='settings'?'active':''}" data-action="go" data-view="settings"><span class="nav-ico">⚙</span>설정</button></div>
 <div class="sidebar-note"><strong>자유롭게 진행하세요</strong><p>90일은 권장 목표기간입니다.<br>단계별 완료 순서는 자유롭습니다.</p></div></aside>`;
}
function renderHeader(){return `<header class="topbar"><button class="hamburger" data-action="open-menu" aria-label="메뉴 열기">☰</button><div class="header-left"><div class="eyebrow">PERSONAL HR WORKSPACE</div><strong>${esc(ws.name)}</strong></div><div class="head-actions"><div class="sync-pill" id="sync-status"></div><button class="btn primary desktop-action" data-action="add-task" data-stage="${ws.stages[0].id}">＋ 업무 추가</button></div></header>`}
function renderHome(){const s=countStats();const recent=ws.activity.slice(0,6);const attention=ws.tasks.filter(t=>['in_progress','waiting'].includes(t.status)).slice(0,7);
 return `<div class="page hero"><div class="intro-label">WORKSPACE OVERVIEW <span>✦</span></div><div class="hero-line"><div><h1>오롯한 HR, 하나씩 완성하기</h1><p>지금 필요한 업무를 확인하고, 실행한 결과를 차곡차곡 쌓아보세요.</p></div><div class="goal-pill">◷ 권장 목표 ${esc(ws.goalDays)}일</div></div>
 <div class="stat-grid"><article class="stat-card accent"><div class="stat-title">전체 진행률 <span>↗</span></div><div class="big-num">${s.percent??'—'}<small>${s.percent===null?'':'%'}</small></div>${progressBar(s.percent)}<p>${s.done}개 완료 / ${s.total}개 적용 업무</p></article>
 <article class="stat-card"><div class="stat-title">전체 업무</div><div class="big-num">${ws.tasks.length}<small>개</small></div><p>4단계 실행 가이드</p><div class="stat-symbol">▦</div></article>
 <article class="stat-card"><div class="stat-title">진행 중</div><div class="big-num">${s.inProgress}<small>개</small></div><p>현재 작업 중인 업무</p><div class="stat-symbol">◔</div></article>
 <article class="stat-card"><div class="stat-title">검토 대기</div><div class="big-num">${s.waiting}<small>개</small></div><p>확인·답변을 기다리는 업무</p><div class="stat-symbol">◷</div></article></div>
 <div class="section-head"><div><h2>단계별 구축 현황</h2><p>순서에 관계없이 원하는 단계부터 진행할 수 있습니다.</p></div></div>
 <div class="stage-cards">${ws.stages.map((st,i)=>{const pr=getStageProgress(ws,st.id);return `<button class="stage-card" data-action="go-stage" data-stage="${st.id}"><div class="stage-card-top"><span class="stage-pill">STEP 0${i+1}</span><span class="forward">↗</span></div><h3>${esc(st.name)}</h3><p>${esc(st.description)}</p><div class="stage-bar-info"><strong>${pr.percent===null?'대상 없음':pr.percent+'%'}</strong><small>${pr.done} / ${pr.total} 완료</small></div>${progressBar(pr.percent)}</button>`}).join('')}</div>
 <div class="two-cols"><section class="panel"><div class="panel-heading"><h2>진행 중 · 대기 업무</h2><button class="text-link" data-action="show-all">전체 업무 보기 →</button></div>${attention.length?attention.map(t=>`<button class="task-list-row" data-action="open-task" data-task="${t.id}"><span>${dots(t.status)}<strong>${esc(t.title)}</strong></span><small>${esc(STATUSES[t.status])}　›</small></button>`).join(''):'<div class="empty-sm">진행 중이거나 대기 중인 업무가 없습니다. 원하는 업무부터 시작해보세요.</div>'}</section>
 <section class="panel"><div class="panel-heading"><h2>최근 작업</h2><small>최근 변경 내용</small></div>${recent.length?recent.map(a=>`<div class="history-row"><span class="history-marker"></span><span>${esc(a.label)}</span><small>${dt(a.time)}</small></div>`).join(''):'<div class="empty-sm">아직 변경 이력이 없습니다. 체크리스트를 사용해보세요.</div>'}</section></div>
 <p class="quiet-note">진행률은 업무 완료 상태를 기준으로 계산하며, ‘해당 없음’ 업무는 제외됩니다. 체크항목 완료와 업무 완료는 별개입니다.</p></div>`;
}
function renderTask(t){if(!t)return `<div class="page"><h2>업무를 선택해주세요.</h2></div>`;
 const stage=ws.stages.find(s=>s.id===t.stageId);const p=getTaskProgress(t);
 return `<div class="page task-page"><div class="breadcrumb"><button data-action="go" data-view="home">홈</button><span>›</span><button data-action="go-stage" data-stage="${t.stageId}">${esc(stage?.name)}</button><span>›</span><strong>${esc(t.title)}</strong></div>
 <div class="task-title-row"><div><div class="intro-label">HR EXECUTION GUIDE</div><h1>${esc(t.title)} ${t.important?'<span class="star">★</span>':''}</h1><p>${esc(t.purpose)}</p></div><div class="task-main-actions">${btn('✎ 업무 편집','edit-task',`data-task="${t.id}"`)}${btn('⋯ 관리','manage-task',`data-task="${t.id}"`)}</div></div>
 <div class="task-status-panel"><div class="task-status-main"><div><label class="input-label">업무 상태</label><select class="input" data-change="task-status" data-task="${t.id}">${choose(STATUSES,t.status)}</select></div><div><label class="input-label">목표일 (선택)</label><input class="input" type="date" value="${esc(t.due)}" data-change="due" data-task="${t.id}"/></div><div class="status-completion"><div><strong>${p.percent===null?'대상 없음':p.percent+'%'}</strong><small>세부 확인률 (${p.done}/${p.total})</small></div>${progressBar(p.percent)}</div></div>${t.due&&t.status!=='complete'&&t.status!=='not_applicable'&&new Date(t.due)<new Date(new Date().toISOString().slice(0,10))?'<small class="danger-text">목표일이 지났습니다. 상태는 자동 변경되지 않습니다.</small>':''}</div>
 <section class="panel guide-panel"><div class="panel-heading"><h2>업무 수행 가이드</h2><span class="chip">직접 수정 가능</span></div><div class="guide-grid"><div><h4>목적</h4><p>${nl(t.purpose)}</p><h4>준비자료</h4><p>${nl(t.prepare)||'별도로 지정된 준비자료가 없습니다.'}</p></div><div><h4>실행 순서</h4><ol class="guidesteps">${(t.steps||'').split('\n').filter(Boolean).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h4>완료 기준</h4><p>${nl(t.criteria)}</p></div></div><div class="outputs"><strong>예상 산출물</strong><span>${esc(t.outputs||'미지정')}</span></div></section>
 <div class="section-head checklist-header"><div><h2>실행 체크리스트</h2><p>체크는 ‘자료 보유’가 아니라 ‘확인 완료’를 의미합니다. 상세 보기에 결과를 기록하세요.</p></div>${btn('＋ 자료 분류 추가','add-group',`data-task="${t.id}"`,'secondary')}</div>
 <div class="group-list">${t.groups.map(g=>{const open=!groupOpen.has(g.id);const active=g.items.filter(i=>!i.na);const c=active.filter(i=>i.done).length;return `<section class="check-group"><div class="group-header"><button class="group-title" data-action="toggle-group" data-group="${g.id}"><span class="fold">${open?'⌄':'›'}</span><strong>${esc(g.title)}</strong><small>${c} / ${active.length} 확인</small></button><div class="group-buttons">${btn('수정','edit-group',`data-task="${t.id}" data-group="${g.id}"`)}${btn('＋ 항목','add-item',`data-task="${t.id}" data-group="${g.id}"`)}${btn('⋯','manage-group',`data-task="${t.id}" data-group="${g.id}"`)}</div></div>
 ${open?`<div class="group-body">${g.items.length?g.items.map((i,idx)=>`<div class="check-row ${i.done?'checked':''} ${i.na?'na':''}"><label class="check-label"><input type="checkbox" data-change="check-item" data-task="${t.id}" data-group="${g.id}" data-item="${i.id}" ${i.done?'checked':''} ${i.na?'disabled':''}/><span>${esc(i.title)}</span></label><div class="check-meta">${i.na?'<span class="micro na-chip">해당 없음</span>':i.availability==='missing'?'<span class="micro missing">미보유</span>':i.availability==='have'?'<span class="micro present">보유</span>':''}${i.result?'<span class="micro filled">기록 있음</span>':''}</div><button class="detail-button" data-action="edit-item" data-task="${t.id}" data-group="${g.id}" data-item="${i.id}">상세 보기 <span>›</span></button></div>`).join(''):'<div class="empty-sm">체크항목이 없습니다.</div>'}<button class="add-item-bottom" data-action="add-item" data-task="${t.id}" data-group="${g.id}">＋ 새 체크항목 추가</button></div>`:''}</section>`}).join('')}</div>
 <div class="bottom-actions"><div><strong>업무 완료는 직접 확인합니다</strong><p>확인 내용과 산출물이 완료 기준을 충족하는지 점검한 후 상태를 변경하세요.</p></div>${t.status==='complete'?btn('↩ 완료 취소','cancel-complete',`data-task="${t.id}"`,'secondary'):btn('✓ 업무 완료 처리','complete-task',`data-task="${t.id}"`,'primary')}</div></div>`;
}
function renderLibrary(){let linked=[];for(const t of ws.tasks)for(const g of t.groups)for(const i of g.items)if(i.link||i.location)linked.push({t,g,i});
 return `<div class="page"><div class="intro-label">REFERENCE LIBRARY</div><h1>자료 모음</h1><p class="subhead">체크항목에서 입력한 자료명·보관 위치·링크를 한곳에서 찾아볼 수 있습니다.</p><section class="panel"><div class="panel-heading"><h2>등록된 자료 ${linked.length}개</h2></div>${linked.length?linked.map(({t,g,i})=>`<div class="resource-row"><div class="resource-icon">▤</div><div><strong>${esc(i.title)}</strong><small>${esc(t.title)} · ${esc(g.title)}</small><p>${esc(i.location||'저장 위치 미지정')}</p>${i.link?`<a href="${esc(safeUrl(i.link))}" target="_blank" rel="noopener noreferrer">관련 자료 링크 열기 ↗</a>`:''}</div><button class="btn ghost" data-action="edit-item" data-task="${t.id}" data-group="${g.id}" data-item="${i.id}">상세 ›</button></div>`).join(''):'<div class="empty-sm">아직 등록된 링크나 보관 위치가 없습니다. 체크항목의 ‘상세 보기’에서 추가할 수 있습니다.</div>'}</section></div>`;
}
function safeUrl(s){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
function renderTrash(){return `<div class="page"><div class="intro-label">RECOVER & RESTORE</div><h1>휴지통</h1><p class="subhead">삭제된 업무·분류·체크항목은 여기에서 복구할 수 있습니다.</p><section class="panel">${ws.trash.length?ws.trash.map(entry=>`<div class="trash-row"><div><strong>${esc(entry.snapshot.title)} </strong><span class="chip">${({task:'업무',group:'자료 분류',item:'체크항목'})[entry.kind]||entry.kind}</span><p>${dt(entry.deletedAt)}</p></div><div>${btn('복원','restore',`data-trash="${entry.id}"`,'secondary')}${btn('영구 삭제','purge',`data-trash="${entry.id}"`,'danger')}</div></div>`).join(''):'<div class="empty-sm">휴지통이 비어 있습니다.</div>'}</section></div>`}
function renderSettings(){return `<div class="page settings-page"><div class="intro-label">YOUR PERSONAL SPACE</div><h1>설정</h1><p class="subhead">백업과 초기화, 기기 연결을 관리할 수 있습니다.</p>
 <div class="settings-grid"><section class="panel"><div class="panel-heading"><h2>작업공간</h2></div><div class="setting-line"><div><strong>작업공간 이름</strong><small>${esc(ws.name)}</small></div>${btn('수정','edit-workspace','','secondary')}</div><div class="setting-line"><div><strong>90일 목표</strong><small>현재 ${esc(ws.goalDays)}일 · 달성 강제 없음</small></div>${btn('수정','edit-workspace','','secondary')}</div><div class="setting-line"><div><strong>데이터 저장 상태</strong><small>${esc(sync.label())} · 각 기기에 영구 저장(앱 데이터 삭제 전까지)</small></div></div></section>
 <section class="panel"><div class="panel-heading"><h2>백업 및 복원</h2></div><p class="muted">모든 메뉴, 수정한 가이드, 체크 기록, 메모를 JSON 파일로 내보냅니다. 서버 연결 인증키는 포함하지 않습니다.</p><div class="setting-actions">${btn('↓ 백업 파일 저장','export-backup','','primary')}${btn('↑ 백업 파일 복원','import-backup','','secondary')}<input type="file" accept="application/json,.json" id="import-file" hidden/></div><p class="mini">브라우저 데이터 삭제 또는 앱 삭제에 대비해 정기적으로 백업하세요.</p></section>
 <section class="panel sync-setting"><div class="panel-heading"><h2>PC · 갤럭시탭 동기화</h2><span class="chip">선택 설정</span></div>${sync.connected()?`<p class="muted">현재 작업공간이 클라우드 서버에 연결되어 있습니다. 같은 작업공간을 다른 기기와 연결할 수 있습니다.</p><div class="read-only"><small>서버 URL</small><strong>${esc(sync.cfg.url)}</strong><small>연결 상태</small><strong>${esc(sync.label())}</strong></div><div class="setting-actions">${btn('지금 동기화','sync-now','','primary')}${btn('다른 기기 연결코드','pair-code','','secondary')}${btn('연결 기기 관리','device-list','','secondary')}</div>${sync.conflict?`<div class="conflict-box"><strong>두 기기의 수정사항이 충돌했습니다.</strong><p>선택하지 않은 쪽의 변경은 서버에 반영되지 않습니다. 먼저 설정에서 로컬 백업을 저장하는 것을 권장합니다.</p><div>${btn('서버 기록 가져오기','resolve-server','','secondary')}${btn('현재 기기 기록 사용','resolve-local','','danger')}</div></div>`:''}<div class="setting-actions">${btn('이 기기 연결 해제','disconnect','','ghost')}</div>`:
 `<p class="muted">기본적으로 이 기기에 기록됩니다. 여러 기기에서 동일한 기록을 보려면 별도 Cloudflare Worker 서버가 필요합니다. GitHub 저장소의 설정 가이드를 참조하세요.</p><div class="setting-actions">${btn('새 동기화 작업공간 만들기','sync-create','','primary')}${btn('다른 기기의 연결코드 입력','sync-join','','secondary')}</div>`}</section>
 <section class="panel"><div class="panel-heading"><h2>데이터 초기화</h2></div><p class="muted">초기화 후에는 취소할 수 없습니다. 먼저 백업해 두세요. 서버 연결 중이면 변경도 서버로 전송됩니다.</p><div class="setting-line"><div><strong>진행 기록 초기화</strong><small>업무 상태·체크·확인결과·메모를 비우고 메뉴와 가이드는 유지</small></div>${btn('초기화','reset-records','','danger')}</div><div class="setting-line"><div><strong>전체 초기화</strong><small>추가·수정한 항목까지 모두 기본 구성으로 복원</small></div>${btn('전체 초기화','reset-all','','danger')}</div></section>
 </div><p class="quiet-note">OROT HR v1.0 · 최초 작업공간 생성일 ${dt(ws.createdAt)}. 개인정보를 직접 기입하는 경우 저장·백업 파일의 접근 권한을 관리하세요.</p></div>`}
function renderList(stageId=null){const arr=ws.tasks.filter(t=>!stageId||t.stageId===stageId);const tasks=selectedFilter(arr);const st=ws.stages.find(s=>s.id===stageId);
 return `<div class="page"><div class="intro-label">HR ACTION DIRECTORY</div><h1>${st?esc(st.name):'전체 업무 목록'}</h1><p class="subhead">업무를 클릭하면 수행 가이드와 실행 체크리스트를 확인할 수 있습니다.</p><div class="filter-bar">${[['all','전체'],...Object.entries(STATUSES)].map(([k,v])=>`<button class="filter-btn ${activeFilter===k?'selected':''}" data-action="filter" data-filter="${k}">${v}</button>`).join('')}</div><div class="panel">${tasks.length?tasks.map(t=>`<button class="directory-row" data-action="open-task" data-task="${t.id}"><span class="dir-title">${dots(t.status)}<strong>${esc(t.title)}</strong><small>${esc(ws.stages.find(s=>s.id===t.stageId)?.name)}</small></span><span class="dir-progress">${getTaskProgress(t).percent??'—'}% 확인</span><span class="status-chip s-${t.status}">${STATUSES[t.status]}</span><span>›</span></button>`).join(''):'<div class="empty-sm">표시할 업무가 없습니다.</div>'}</div>${stageId?`<div class="bottom-actions">${btn('＋ 이 단계에 업무 추가','add-task',`data-stage="${stageId}"`,'primary')}${btn('단계 이름 수정','edit-stage',`data-stage="${stageId}"`,'secondary')}</div>`:''}</div>`}
function renderSearch(){const q=search.trim().toLocaleLowerCase('ko-KR');const found=ws.tasks.filter(t=>[t.title,t.purpose,t.criteria,...t.groups.flatMap(g=>[g.title,...g.items.map(i=>i.title+' '+i.result+' '+i.followUp)])].join(' ').toLowerCase().includes(q));return `<div class="page"><div class="intro-label">SEARCH RESULTS</div><h1>“${esc(search)}” 검색</h1><p class="subhead">${found.length}개 업무가 검색되었습니다.</p><div class="panel">${found.length?found.map(t=>`<button class="directory-row" data-action="open-task" data-task="${t.id}"><span class="dir-title">${dots(t.status)}<strong>${esc(t.title)}</strong><small>${esc(ws.stages.find(s=>s.id===t.stageId)?.name)}</small></span><span>›</span></button>`).join(''):'<div class="empty-sm">검색 결과가 없습니다. 다른 단어를 입력해보세요.</div>'}</div></div>`}
function render(){const app=$('#app');app.innerHTML=`${renderNav()}<div class="main-layout">${renderHeader()}<div class="search-region"><label class="searchbox">⌕ <input id="global-search" placeholder="업무·체크항목·메모 검색" value="${esc(search)}" autocomplete="off" aria-label="업무 검색"/></label><span class="saved-tag">✓ 자동 저장</span></div><main id="page-body">${search.trim()?renderSearch():view==='home'?renderHome():view==='task'?renderTask(taskById(selectedId)):view==='library'?renderLibrary():view==='trash'?renderTrash():view==='settings'?renderSettings():view==='list'?renderList(currentStage):renderHome()}</main><footer class="footer">OROT HR · Better People, Better Practice <span>개인용 HR 구축 도구</span></footer></div>${sideOpen?'<div class="overlay" data-action="close-menu"></div>':''}`;updateSync();}
let currentStage=null;render();

function dialog(title,fields,onSave,opts={}){
 const dlg=$('#dialog');dlg.innerHTML=`<form method="dialog" id="edit-form"><div class="modal-head"><div><small>OROT HR</small><h2>${esc(title)}</h2></div><button class="close" value="cancel" type="button" data-action="close-dialog">✕</button></div><div class="modal-body">${fields}</div><div class="modal-footer"><button class="btn ghost" value="cancel" type="button" data-action="close-dialog">취소</button><button class="btn primary" type="submit">${opts.saveLabel||'저장'}</button></div></form>`;
 dlg.showModal();const form=$('#edit-form');form.addEventListener('submit',async ev=>{ev.preventDefault();const fd=new FormData(form);try{const ok=await onSave(Object.fromEntries(fd.entries()));if(ok!==false)dlg.close()}catch(e){toast(e.message||'저장에 실패했습니다.')}});
}
const inp=(name,label,val='',opt={})=>`<label class="field"><span>${esc(label)}</span>${opt.area?`<textarea name="${name}" rows="${opt.rows||3}" ${opt.required?'required':''} placeholder="${esc(opt.placeholder||'')}">${esc(val)}</textarea>`:`<input name="${name}" type="${opt.type||'text'}" value="${esc(val)}" ${opt.required?'required':''} placeholder="${esc(opt.placeholder||'')}"/>`}</label>`;
const sel=(name,label,opts,v)=>`<label class="field"><span>${esc(label)}</span><select name="${name}">${choose(opts,v)}</select></label>`;
function editTask(t,stageId){const editing=!!t;
 dialog(editing?'업무 편집':'새 업무 추가',inp('title','업무명',t?.title,{required:true})+inp('purpose','업무 목적',t?.purpose,{area:true})+inp('prepare','준비자료',t?.prepare,{area:true,rows:2})+inp('steps','실행 순서 (한 줄에 하나씩)',t?.steps,{area:true,rows:5})+inp('criteria','완료 기준',t?.criteria,{area:true})+inp('outputs','예상 산출물',t?.outputs)+sel('stageId','소속 단계',Object.fromEntries(ws.stages.map(s=>[s.id,s.name])),t?.stageId||stageId)+inp('memo','업무 메모',t?.memo,{area:true,rows:2}),d=>{if(!d.title.trim())throw Error('업무명을 입력하세요.');const id=t?.id||uid();change(editing?`업무 가이드 수정: ${d.title}`:`새 업무 추가: ${d.title}`,()=>{const obj=t||{id,groups:[],status:'not_started',due:'',important:false,updatedAt:new Date().toISOString()};Object.assign(obj,d,{updatedAt:new Date().toISOString()});if(!editing)ws.tasks.push(obj)});selectTask(id)});
}
function editGroup(t,g){dialog(g?'자료 분류 수정':'새 자료 분류',inp('title','분류명',g?.title,{required:true}),d=>{if(!d.title.trim())throw Error('분류명을 입력해주세요.');change(`자료 분류 ${g?'수정':'추가'}: ${d.title}`,()=>{if(g)g.title=d.title;else t.groups.push({id:uid(),title:d.title,items:[]})})})}
function editItem(t,g,i){
 const fields=`<div class="field-grid">${inp('title','확인 항목명',i?.title,{required:true})}${sel('availability','자료 보유 여부',{unknown:'확인 전',have:'보유',missing:'미보유'},i?.availability||'unknown')}${sel('obtained','자료 확보 상태',{unknown:'확인 전',obtained:'확보 완료',requested:'요청 중',unavailable:'확보 불가'},i?.obtained||'unknown')}${inp('owner','자료 담당자',i?.owner)}${inp('location','보관 위치',i?.location)}${inp('referenceDate','자료 기준일',i?.referenceDate,{type:'date'})}${inp('link','참고 자료 URL (https://...)',i?.link,{type:'url'})}${sel('na','업무 적용 여부',{no:'적용 항목',yes:'해당 없음'},i?.na?'yes':'no')}</div>${inp('guide','확인 방법·설명',i?.guide,{area:true,rows:2})}${inp('result','확인 결과',i?.result,{area:true})}${inp('followUp','후속 조치',i?.followUp,{area:true})}${inp('naReason','해당 없음 사유',i?.naReason,{area:true,rows:2})}${i?`<div class="manage-grid">${btn('↑ 항목 위로','move-up',`data-kind="item" data-task="${t.id}" data-group="${g.id}" data-item="${i.id}"`)}${btn('↓ 항목 아래로','move-down',`data-kind="item" data-task="${t.id}" data-group="${g.id}" data-item="${i.id}"`)}${btn('항목 삭제','delete-item',`data-task="${t.id}" data-group="${g.id}" data-item="${i.id}"`,'danger')}</div>`:''}`;
 dialog(i?'체크항목 상세 기록':'새 체크항목 추가',fields,d=>{
  if(!d.title.trim())throw Error('항목명을 입력해주세요.');
  if(d.link&&safeUrl(d.link)==='#')throw Error('http:// 또는 https:// URL만 입력할 수 있습니다.');
  if(d.na==='yes'&&!d.naReason.trim())throw Error('해당 없음 사유를 작성해주세요.');
  change(`${t.title} · 항목 ${i?'수정':'추가'}: ${d.title}`,()=>{
   const obj=i||{id:uid(),done:false,doneAt:null,updatedAt:null};const wasChecked=Boolean(obj.done);
   Object.assign(obj,d,{na:d.na==='yes',updatedAt:new Date().toISOString()});
   if(obj.na){obj.done=false;obj.doneAt=null;}
   if(wasChecked && obj.na && t.status==='complete')t.status='in_progress';
   if(!i)g.items.push(obj);t.updatedAt=new Date().toISOString();
  });
 });
}
function handleAction(a,el){const task=taskById(el.dataset.task),stageId=el.dataset.stage,group=groupById(task,el.dataset.group),item=itemById(task,el.dataset.group,el.dataset.item);
 switch(a){
 case 'go':go(el.dataset.view);break;case 'open-task':selectTask(el.dataset.task);break;case 'go-stage':currentStage=stageId;activeFilter='all';go('list');break;case 'show-all':currentStage=null;activeFilter='all';go('list');break;
 case 'filter':activeFilter=el.dataset.filter;render();break;
 case 'toggle-stage':expanded.has(stageId)?expanded.delete(stageId):expanded.add(stageId);render();break;
 case 'toggle-group':groupOpen.has(el.dataset.group)?groupOpen.delete(el.dataset.group):groupOpen.add(el.dataset.group);render();break;
 case 'open-menu':sideOpen=true;render();break;case 'close-menu':sideOpen=false;render();break;case 'close-dialog':$('#dialog').close();break;
 case 'add-task':editTask(null,stageId||ws.stages[0].id);break;case 'edit-task':editTask(task);break;
 case 'edit-stage':{const s=ws.stages.find(s=>s.id===stageId);if(s)dialog('단계 이름 수정',inp('name','단계 이름',s.name,{required:true})+inp('description','단계 설명',s.description,{area:true}),d=>{if(!d.name.trim())throw Error('단계 이름을 입력하세요.');change('단계 이름 수정',()=>Object.assign(s,d))});break;}
 case 'add-group':editGroup(task,null);break;case 'edit-group':editGroup(task,group);break;case 'add-item':editItem(task,group,null);break;case 'edit-item':editItem(task,group,item);break;
 case 'complete-task':{const p=getTaskProgress(task);if(p.total && p.done<p.total && !confirmDanger(`체크항목이 ${p.done}/${p.total}개 확인되었습니다. 완료 기준을 직접 확인하고 업무를 완료 처리하시겠습니까?`))break;change(`업무 완료: ${task.title}`,()=>{task.status='complete';task.updatedAt=new Date().toISOString()});toast('업무를 완료 처리했습니다.');break;}
 case 'cancel-complete':change(`업무 완료 취소: ${task.title}`,()=>task.status='in_progress');break;
 case 'manage-task':manageEntity('task',task);break;case 'manage-group':manageEntity('group',task,group);break;
 case 'restore':restoreEntry(el.dataset.trash);break;case 'purge':purgeEntry(el.dataset.trash);break;
 case 'edit-workspace':dialog('작업공간 수정',inp('name','이름',ws.name,{required:true})+inp('goalDays','목표기간 (일)',ws.goalDays,{type:'number'}),d=>{const days=Number(d.goalDays);if(!d.name.trim()||days<1||days>3650)throw Error('이름과 올바른 목표일수를 입력하세요.');change('작업공간 정보 변경',()=>{ws.name=d.name.trim();ws.goalDays=days})});break;
 case 'export-backup':exportBackup();break;case 'import-backup':$('#import-file')?.click();break;
 case 'reset-records':resetRecords();break;case 'reset-all':resetAll();break;
 case 'sync-create':syncCreate();break;case 'sync-join':syncJoin();break;case 'sync-now':if(sync.dirty)sync.push();else sync.pull();toast('동기화 요청을 시작했습니다.');break;
 case 'pair-code':pairCode();break;case 'device-list':deviceList();break;case 'disconnect':if(confirmDanger('서버 연결만 해제합니다. 이 기기의 데이터는 그대로 남습니다. 다른 기기에는 변경사항이 전달되지 않습니다.')){sync.disconnect();render()}break;
 case 'resolve-server':resolve(true);break;case 'resolve-local':resolve(false);break;
 case 'move-up':case 'move-down':moveItem(el.dataset.kind,task,group,item,a==='move-up'?-1:1);break;
 case 'delete-task':deleteEntity('task',task);break;case 'delete-group':deleteEntity('group',task,group);break;case 'delete-item':deleteEntity('item',task,group,item);break;
 case 'clone-task':{const idx=ws.tasks.indexOf(task);change(`업무 복제: ${task.title}`,()=>{const copy=structuredClone(task);copy.id=uid();copy.title+=' (복제)';copy.status='not_started';copy.groups.forEach(g=>{g.id=uid();g.items.forEach(i=>{i.id=uid();i.done=false;i.doneAt=null;i.result='';i.followUp='';})});ws.tasks.splice(idx+1,0,copy)});break;}
 case 'toggle-important':change('중요 업무 표시 변경',()=>{task.important=!task.important});break;
 }
}
function manageEntity(kind,t,g){const name=kind==='task'?t.title:g.title;
 dialog(`${name} · 관리`,kind==='task'?`<p class="muted">업무의 복제·정렬·삭제 등을 실행할 수 있습니다.</p><div class="manage-grid">${btn(t.important?'★ 중요 해제':'☆ 중요 표시','toggle-important',`data-task="${t.id}"`)}${btn('업무 복제','clone-task',`data-task="${t.id}"`)}${btn('위로 이동','move-up',`data-kind="task" data-task="${t.id}"`)}${btn('아래로 이동','move-down',`data-kind="task" data-task="${t.id}"`)}${btn('휴지통으로 이동','delete-task',`data-task="${t.id}"`,'danger')}</div>`:
 `<p class="muted">분류 내의 체크항목도 함께 이동 또는 복구됩니다.</p><div class="manage-grid">${btn('위로 이동','move-up',`data-kind="group" data-task="${t.id}" data-group="${g.id}"`)}${btn('아래로 이동','move-down',`data-kind="group" data-task="${t.id}" data-group="${g.id}"`)}${btn('휴지통으로 이동','delete-group',`data-task="${t.id}" data-group="${g.id}"`,'danger')}</div>`,()=>true,{saveLabel:'닫기'});
}
function moveItem(kind,t,g,i,dir){change('순서 변경',()=>{const arr=kind==='task'?ws.tasks:kind==='group'?t.groups:g.items;const idx=arr.indexOf(kind==='task'?t:kind==='group'?g:i);let next=idx+dir;if(kind==='task'){while(next>=0&&next<arr.length&&arr[next].stageId!==t.stageId)next+=dir;}if(next<0||next>=arr.length)return;[arr[idx],arr[next]]=[arr[next],arr[idx]]});$('#dialog')?.close();}
function deleteEntity(kind,t,g,i){const target=kind==='task'?t:kind==='group'?g:i;if(!confirmDanger(`‘${target.title}’을(를) 휴지통으로 이동할까요? 휴지통에서 복구할 수 있습니다.`))return;
 change(`휴지통 이동: ${target.title}`,()=>{ws.trash.unshift({id:uid(),kind,parentTaskId:t?.id||null,parentGroupId:g?.id||null,snapshot:structuredClone(target),deletedAt:new Date().toISOString()});const arr=kind==='task'?ws.tasks:kind==='group'?t.groups:g.items;arr.splice(arr.indexOf(target),1)});$('#dialog')?.close();if(kind==='task'){selectedId=ws.tasks[0]?.id;go('home')}}
function restoreEntry(id){const ent=ws.trash.find(e=>e.id===id);if(!ent)return;const t=taskById(ent.parentTaskId),g=groupById(t,ent.parentGroupId);if(ent.kind==='group'&&!t||ent.kind==='item'&&!g){toast('상위 업무 또는 분류를 먼저 복구해주세요.');return;}change(`휴지통 복구: ${ent.snapshot.title}`,()=>{if(ent.kind==='task')ws.tasks.push(ent.snapshot);else if(ent.kind==='group')t.groups.push(ent.snapshot);else g.items.push(ent.snapshot);ws.trash=ws.trash.filter(e=>e.id!==id)})}
function purgeEntry(id){if(confirmDanger('영구 삭제 후에는 복구할 수 없습니다. 정말 삭제하시겠습니까?'))change('휴지통 영구 삭제',()=>ws.trash=ws.trash.filter(e=>e.id!==id))}
function exportBackup(){const name=`OROT_HR_backup_${new Date().toISOString().slice(0,10)}.json`;const data=JSON.stringify({format:'OROT-HR-BACKUP',exportedAt:new Date().toISOString(),workspace:ws},null,2);downloadFile(name,'application/json',data);toast('백업 파일을 저장했습니다.');}
function downloadFile(name,type,data){const blob=new Blob([data],{type});const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function resetRecords(){if(!confirmDanger('모든 진행 상태·체크 결과·확인 메모를 초기화합니다. 수정한 가이드와 체크항목은 유지됩니다. 먼저 백업하셨습니까?'))return;
 change('진행 기록 초기화',()=>{ws.tasks.forEach(t=>{t.status='not_started';t.due='';t.memo='';t.groups.forEach(g=>g.items.forEach(i=>Object.assign(i,{done:false,na:false,naReason:'',availability:'unknown',obtained:'unknown',owner:'',location:'',referenceDate:'',result:'',followUp:'',link:'',doneAt:null})))})});toast('진행 기록이 초기화되었습니다.')}
function resetAll(){if(!confirmDanger('모든 개인 변경과 실행 기록을 삭제하고 기본 4단계 구성으로 돌아갑니다. 정말 진행하시겠습니까?'))return;if(!confirmDanger('마지막 확인: 전체 초기화를 실행할까요?'))return;change('전체 초기화',()=>{ws=createWorkspace()});go('home')}
async function resolve(server){if(!confirmDanger(server?'서버 데이터를 가져오면 이 기기의 전송되지 않은 변경사항을 덮어씁니다. 계속하시겠습니까?':'현재 기기 데이터로 서버 내용을 덮어씁니다. 계속하시겠습니까?'))return;try{await sync.resolveConflict(server);render()}catch(e){toast('충돌 처리 실패: '+e.message)}}
function syncCreate(){dialog('새 동기화 작업공간 생성',`<p class="muted">Cloudflare에 직접 배포한 Worker 서버 주소를 입력합니다. 현재 이 기기의 기록을 최초 서버 데이터로 올립니다.</p>${inp('url','동기화 서버 주소','',{required:true,placeholder:'https://orot-hr-sync.계정.workers.dev'})}${inp('name','이 기기 이름','PC')}${inp('setupKey','Cloudflare에 등록한 최초 설정키','',{required:true})}`,async d=>{if(sync.connected())throw Error('이미 서버에 연결되어 있습니다.');await sync.createServer(d.url,d.name,d.setupKey);toast('서버에 작업공간을 생성했습니다.');render()})}
function syncJoin(){dialog('다른 기기 작업공간 연결',`<p class="muted">기존 기기의 설정에서 ‘다른 기기 연결코드’를 발급받으세요. 연결하면 <strong>이 기기의 현재 기록은 서버 기록으로 교체</strong>됩니다. 먼저 백업하세요.</p>${inp('url','동기화 서버 주소','',{required:true,placeholder:'https://orot-hr-sync.계정.workers.dev'})}${inp('code','연결코드 (12자리)','',{required:true})}${inp('name','이 기기 이름','갤럭시탭')}`,async d=>{if(!confirmDanger('이 기기 기록을 서버 기록으로 교체합니다. 현재 기록을 백업했습니까?'))return false;await sync.pair(d.url,d.code,d.name);toast('기기 연결을 완료했습니다.');render()})}
async function pairCode(){try{const p=await sync.createPair();dialog('다른 기기 연결하기',`<p class="muted">다른 기기에서 설정 → 연결코드 입력 메뉴를 이용하세요. 코드가 만료되면 새로 발급할 수 있습니다.</p><div class="pair-code">${esc(p.code)}</div><p class="muted">유효기간: 10분 · 1회만 사용 가능</p><div class="read-only"><small>동기화 서버 URL</small><strong>${esc(sync.cfg.url)}</strong></div>`,()=>true,{saveLabel:'확인'})}catch(e){toast('코드 발급 실패: '+e.message)}}
async function deviceList(){try{const devices=await sync.devices();dialog('연결된 기기',`<p class="muted">접근 권한을 해제한 기기는 이후 서버 데이터를 읽거나 저장할 수 없습니다.</p>${devices.map(d=>`<div class="device-row"><div><strong>${esc(d.name)}</strong><small>${esc(d.id===sync.cfg.deviceId?'이 기기':dt(d.createdAt))}</small></div>${d.id===sync.cfg.deviceId?'<span class="chip">현재 기기</span>':btn('연결 해제','revoke-device',`data-device="${esc(d.id)}"`,'danger')}</div>`).join('')}`,()=>true,{saveLabel:'닫기'})}catch(e){toast('기기 목록 조회 실패: '+e.message)}}
async function actionRevoke(el){const id=el.dataset.device;if(!confirmDanger('이 기기의 서버 접근을 해제할까요?'))return;try{await sync.revoke(id);$('#dialog').close();deviceList()}catch(e){toast('연결 해제 실패: '+e.message)}}

document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(!el)return;ev.preventDefault();const a=el.dataset.action;if(a==='revoke-device'){actionRevoke(el);return;}handleAction(a,el)});
document.addEventListener('change',ev=>{const el=ev.target;
 if(el.id==='import-file'){const file=el.files?.[0];if(!file)return;file.text().then(raw=>{let data;try{data=JSON.parse(raw)}catch{throw Error('JSON 파일 형식이 아닙니다.')}if(data.format!=='OROT-HR-BACKUP'||!isValidWorkspace(data.workspace))throw Error('OROT HR 백업 파일이 아닙니다.');if(!confirmDanger('복원하면 현재 작업공간 전체가 백업 데이터로 교체됩니다. 진행할까요?'))return;change('백업 파일 복원',()=>{ws=structuredClone(data.workspace)});go('home');toast('백업 복원이 완료되었습니다.');}).catch(e=>toast('복원 실패: '+e.message));return;}
 const t=taskById(el.dataset.task);if(!t)return;
 if(el.dataset.change==='task-status'){if(el.value==='complete'&&!confirmDanger('완료 기준과 산출물을 확인하고 완료 상태로 변경합니까?')){render();return;}change(`업무 상태 변경: ${t.title}`,()=>{t.status=el.value;t.updatedAt=new Date().toISOString()});}
 if(el.dataset.change==='due'){change(`목표일 변경: ${t.title}`,()=>t.due=el.value)}
 if(el.dataset.change==='check-item'){const i=itemById(t,el.dataset.group,el.dataset.item);change(`체크 ${el.checked?'완료':'해제'}: ${i.title}`,()=>{i.done=el.checked;i.doneAt=i.done?new Date().toISOString():null;i.updatedAt=new Date().toISOString();if(!i.done&&t.status==='complete')t.status='in_progress';if(i.done&&t.status==='not_started')t.status='in_progress';t.updatedAt=new Date().toISOString()})}
});
document.addEventListener('input',ev=>{if(ev.target.id==='global-search'){search=ev.target.value;$('#page-body').innerHTML=search.trim()?renderSearch():view==='home'?renderHome():view==='task'?renderTask(taskById(selectedId)):view==='library'?renderLibrary():view==='trash'?renderTrash():view==='settings'?renderSettings():renderList(currentStage)}});
$('#dialog').addEventListener('click',ev=>{if(ev.target.id==='dialog')$('#dialog').close()});
window.addEventListener('beforeunload',()=>{if(sync.connected()&&sync.dirty){/* 로컬 데이터는 이미 저장됨; 후속 실행 시 재전송 */}});
if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('./sw.js').catch(console.warn);
