// DOM-free app smoke test: validates markup creation, task navigation and persistence actions.
import assert from 'node:assert/strict';
const store=new Map(),listeners={};
const fakeEl=()=>({innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){}},addEventListener(){},close(){},showModal(){}});
const app=fakeEl(),dlg=fakeEl(),toast=fakeEl();
const query=s=>({'#app':app,'#dialog':dlg,'#toast':toast})[s]||null;
globalThis.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};
globalThis.document={querySelector:query,addEventListener:(name,fn)=>{listeners[name]=fn},hidden:false};
globalThis.window={addEventListener(){},scrollTo(){},confirm(){return true}};
Object.defineProperty(globalThis,'navigator',{value:{},configurable:true});globalThis.location={protocol:'https:'};
await import('../app/app.js');
assert.match(app.innerHTML,/오롯한 HR, 하나씩 완성하기/);
const snapshot=JSON.parse(store.get('orot_hr_workspace_v1'));
assert.equal(snapshot.stages.length,4);assert.equal(snapshot.tasks.length,32);
assert.ok(snapshot.tasks[0].groups.length===7);
const task=snapshot.tasks[0],group=task.groups[0],item=group.items[0];
const trigger=(type,dataset,extras={})=>{
 const elem={dataset,closest(){return this},...extras};
 listeners[type]({target:elem,preventDefault(){}});
};
trigger('click',{action:'open-task',task:task.id});
assert.match(app.innerHTML,/기존 인사자료 수집/);
assert.match(app.innerHTML,/현재 조직도 확인/);
trigger('change',{change:'check-item',task:task.id,group:group.id,item:item.id},{checked:true});
let after=JSON.parse(store.get('orot_hr_workspace_v1'));
assert.equal(after.tasks[0].groups[0].items[0].done,true);
assert.equal(after.tasks[0].status,'in_progress');
trigger('change',{change:'check-item',task:task.id,group:group.id,item:item.id},{checked:false});
after=JSON.parse(store.get('orot_hr_workspace_v1'));
assert.equal(after.tasks[0].groups[0].items[0].done,false);
trigger('click',{action:'delete-item',task:task.id,group:group.id,item:item.id});
after=JSON.parse(store.get('orot_hr_workspace_v1'));
assert.equal(after.trash.length,1);
assert.equal(after.tasks[0].groups[0].items.length,4);
trigger('click',{action:'restore',trash:after.trash[0].id});
after=JSON.parse(store.get('orot_hr_workspace_v1'));
assert.equal(after.trash.length,0);
assert.equal(after.tasks[0].groups[0].items.length,5);
trigger('click',{action:'go',view:'settings'});
assert.match(app.innerHTML,/백업 및 복원/);
console.log('APP SMOKE PASS:',{stages:after.stages.length,tasks:after.tasks.length,firstGroupItems:after.tasks[0].groups[0].items.length,activity:after.activity.length});
process.exit(0);
